Document: cppunit
Title: Debian cppunit Manual
Author: <insert document author here>
Abstract: This manual describes what cppunit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cppunit/cppunit.sgml.gz

Format: postscript
Files: /usr/share/doc/cppunit/cppunit.ps.gz

Format: text
Files: /usr/share/doc/cppunit/cppunit.text.gz

Format: HTML
Index: /usr/share/doc/cppunit/html/index.html
Files: /usr/share/doc/cppunit/html/*.html
